project:
  type: website

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


website:
  title: "Mise en production"
  navbar:
    background: "#447099"
    search: true
    align: center
    collapse-below: lg
    left:
      - href: chapters/introduction.qmd
        text: Introduction
      - text: Les bases
        menu:
          - href: /website/chapters/linux-101.html
            text: Linux 101
          - href: /website/chapters/git.html
            text: Git
      - text: Bonnes pratiques de développement
        menu:
          - href: /website/chapters/code-quality.html
            text: Qualité du code
          - href: /website/chapters/projects-architecture.html
            text: Structure des projets
          - href: /website/chapters/big-data.html
            text: Traitement des données volumineuses
          - href: /website/chapters/portability.html
            text: Portabilité
      - text: Mise en production
        menu:
          - href: /website/chapters/deployment.html
            text: Déploiement
          - href: /website/chapters/mlops.html
            text: MLOps
      - href: chapters/application.html
        text: Application
      - href: https://ensae-reproductibilite.github.io/slides/
        text: Slides
      - text: Projets
        menu:
          - href: /website/chapters/evaluation.html
            text: Modalités d'évaluation
          - href: /website/chapters/galerie.html
            text: Galerie des projets passés
      - icon: github
        menu:
          - text: Site web
            url:  https://github.com/ensae-reproductibilite/website
          - text: Slides
            url:  https://github.com/ensae-reproductibilite/slides
          - text: Application fil rouge
            url:  https://github.com/ensae-reproductibilite/application

